create database szkola
go
use szkola
go
CREATE TABLE uczniowie(
	[id] [int] IDENTITY(1,1) NOT NULL,
	[imie] [nvarchar](50) NULL,
	[p³eæ] [nvarchar](50) NULL,
 CONSTRAINT [PK_uczniowie] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO