//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_zaliczeniowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmiot
    {
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> nauczyciel { get; set; }
        public Nullable<int> klasa { get; set; }
    
        public virtual Klasa Klasa1 { get; set; }
        public virtual nauczyciele nauczyciele { get; set; }
    }
}
